# Generated by Django 4.2.3 on 2023-07-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Логин покупателя"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Строка, представляющая название дрaгоценного камня",
                        max_length=255,
                        verbose_name="Наименование",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Сумма сделки"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(verbose_name="Количество товара, шт."),
                ),
                (
                    "date",
                    models.DateTimeField(
                        verbose_name="Дата и время регистрации сделки"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_deals",
                        to="deal_api.customer",
                        verbose_name="Логин покупателя",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_deals",
                        to="deal_api.gem",
                        verbose_name="Наименование товара",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="gems",
            field=models.ManyToManyField(
                null=True,
                related_name="customers",
                through="deal_api.Deal",
                to="deal_api.gem",
                verbose_name="Приобретённые драгоценные камни",
            ),
        ),
    ]
