# Generated by Django 4.2.3 on 2023-08-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("deal_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_gems",
                to="deal_api.customer",
                verbose_name="Логин покупателя",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gem_customers",
                to="deal_api.gem",
                verbose_name="Наименование товара",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма сделки"
            ),
        ),
    ]
